export const teamMembers = [
  {
    id: 1,
    name: "Team Member 1",
    role: "Architect",
    image: "./Images/INDIVIDUAL/_MG_3594.jpg",
  },
  {
    id: 2,
    name: "Team Member 2",
    role: "Interior Designer",
    image: "./Images/INDIVIDUAL/_MG_3602.jpg",
  },
  {
    id: 3,
    name: "Prajakta More",
    role: "Team Leader",

    image: "./Images/INDIVIDUAL/_MG_3604.jpg",
  },
  {
    id: 4,
    name: "Team Member 4",
    role: "Architect",
    image: "./Images/INDIVIDUAL/_MG_3607.jpg ",
  },
  {
    id: 5,
    name: "Team Member 5",
    role: "Interior Designer",
    image: "./Images/INDIVIDUAL/_MG_3611.jpg",
  },
  {
    id: 6,
    name: "Team Member 6",
    role: "Architect",
    image: "./Images/INDIVIDUAL/_MG_3616.jpg",
  },
  {
    id: 7,
    name: "Team Member 7",
    role: "Architect",
    image: "./Images/INDIVIDUAL/_MG_3621.jpg",
  },
  {
    id: 8,
    name: "Team Member 8",
    role: "Architect",
    image: "./Images/INDIVIDUAL/_MG_3622.jpg",
  },
  {
    id: 9,
    name: "Team Member 9",
    role: "Architect",
    image: "./Images/INDIVIDUAL/_MG_3630.jpg",
  },
  {
    id: 10,
    name: "Team Member 10",
    role: "Architect",
    image: "./Images/INDIVIDUAL/_MG_3634.jpg",
  },
  {
    id: 11,
    name: "Team Member 11",
    role: "Architect",
    image: "./Images/INDIVIDUAL/_MG_3638.jpg",
  },
  {
    id: 12,
    name: "Team Member 12",
    role: "Architect",
    image: "./Images/INDIVIDUAL/_MG_3640.jpg",
  },
  {
    id: 13,
    name: "Team Member 13",
    role: "Architect",
    image: "./Images/INDIVIDUAL/_MG_3645.jpg",
  },
  {
    id: 14,
    name: "Team Member 14",
    role: "Architect",
    image: "./Images/INDIVIDUAL/_MG_3653.jpg",
  },
  {
    id: 15,
    name: "Team Member 15",
    role: "Architect",
    image: "./Images/INDIVIDUAL/_MG_3654.jpg",
  },
  {
    id: 16,
    name: "Team Member 16",
    role: "Architect",
    image: "./Images/INDIVIDUAL/_MG_3658.jpg",
  },
  {
    id: 17,
    name: "Team Member 17",
    role: "Architect",
    image: "./Images/INDIVIDUAL/_MG_3664.jpg",
  },
  {
    id: 18,
    name: "Team Member 18",
    role: "Architect",
    image: "./Images/INDIVIDUAL/_MG_3668.jpg",
  },
  {
    id: 19,
    name: "Team Member 19",
    role: "Architect",
    image: "./Images/INDIVIDUAL/_MG_3673.jpg",
  },
  {
    id: 20,
    name: "Team Member 20",
    role: "Architect",
    image: "./Images/INDIVIDUAL/_MG_3676.jpg",
  },
  {
    id: 21,
    name: "Team Member 21",
    role: "Architect",
    image: "./Images/INDIVIDUAL/_MG_3682.jpg",
  },
  {
    id: 22,
    name: "Team Member 22",
    role: "Architect",
    image: "./Images/INDIVIDUAL/_MG_3685.jpg",
  },
  {
    id: 23,
    name: "Team Member 23",
    role: "Architect",
    image: "./Images/INDIVIDUAL/_MG_3686.jpg",
  },
  {
    id: 24,
    name: "Team Member 24",
    role: "Architect",
    image: "./Images/INDIVIDUAL/_MG_3692.jpg",
  },
  {
    id: 25,
    name: "Team Member 25",
    role: "Architect",
    image: "./Images/INDIVIDUAL/_MG_3696.jpg",
  },
  {
    id: 26,
    name: "Team Member 26",
    role: "Architect",
    image: "./Images/INDIVIDUAL/_MG_3702.jpg",
  },
  {
    id: 27,
    name: "Team Member 27",
    role: "Architect",
    image: "./Images/INDIVIDUAL/_MG_3704.jpg",
  },
  {
    id: 28,
    name: "Team Member 28",
    role: "Architect",
    image: "./Images/INDIVIDUAL/_MG_3706.jpg",
  },
  {
    id: 29,
    name: "Team Member 29",
    role: "Architect",
    image: "./Images/INDIVIDUAL/_MG_3712.jpg",
  },
  {
    id: 30,
    name: "Team Member 30",
    role: "Architect",
    image: "./Images/INDIVIDUAL/_MG_3715.jpg",
  },
];

export const ownerMember = [
  {
    id: 1,
    name: " Member 1",
    role: "Architect",
    image: "./Images/OwnerImages/_MG_3882.jpg",
  },
  {
    id: 2,
    name: " Member 2",
    role: "Interior Designer",
    image: "./Images/OwnerImages/_MG_3936.jpg",
  },
  {
    id: 3,
    name: "Member 3",
    role: "Team Leader",
    designation: "Interior Designer",
    image: "./Images/OwnerImages/_MG_3923.jpg",
  },
];
